"""categories_audit

Revision ID: 2e8a931e9aab
Revises: bc6a4ce7a2b7
Create Date: 2026-01-14 12:13:28.976904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8a931e9aab'
down_revision: Union[str, None] = 'bc6a4ce7a2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_categories_org_name')
    )
    op.create_index('ix_categories_org_name', 'categories', ['org_id', 'name'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_org_created', 'audit_logs', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_audit_org_entity', 'audit_logs', ['org_id', 'entity_type', 'entity_id'], unique=False)
    op.add_column('products', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['updated_by_user_id'], ['id'])
    op.add_column('sales', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.add_column('sales', sa.Column('updated_by_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sales', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'sales', 'users', ['created_by_user_id'], ['id'])
    op.add_column('stock_movements', sa.Column('actor_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'users', ['actor_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'actor_user_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'updated_by_user_id')
    op.drop_column('sales', 'created_by_user_id')
    op.drop_column('sales', 'updated_at')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'updated_by_user_id')
    op.drop_column('products', 'created_by_user_id')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'category_id')
    op.drop_index('ix_audit_org_entity', table_name='audit_logs')
    op.drop_index('ix_audit_org_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_categories_org_name', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###